version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - db
            - redis
        networks:
            - app_network

    db:
        image: mysql:8.0
        container_name: mysql_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        command: --default-authentication-plugin=mysql_native_password --max-connections=1000
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - app_network

    redis:
        image: redis:alpine
        container_name: redis
        restart: unless-stopped
        networks:
            - app_network

    websockets:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_websockets
        restart: unless-stopped
        working_dir: /var/www
        command: php artisan websockets:serve
        depends_on:
            - app
        networks:
            - app_network
        ports:
            - '6001:6001'

    queue:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_queue
        restart: unless-stopped
        working_dir: /var/www
        command: php artisan queue:work --tries=3 --timeout=90
        depends_on:
            - app
        networks:
            - app_network

    schedule:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_schedule
        restart: unless-stopped
        working_dir: /var/www
        command: /bin/sh -c "while :; do php artisan schedule:run --verbose --no-interaction; sleep 60; done"
        depends_on:
            - app
        networks:
            - app_network

    nginx:
        image: nginx:alpine
        container_name: nginx_server
        restart: unless-stopped
        ports:
            - '80:80'
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - app_network

volumes:
    db_data:

networks:
    app_network:
