<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
use App\Models\Maintenance\NearLocationFilter;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('near_location_filters', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->string('code')->unique();
            $table->longText('description')->nullable();
            $table->uuid('created_by')->nullable();
            $table->uuid('updated_by')->nullable();
            $table->foreign('created_by')->references('id')->on('users');
            $table->foreign('updated_by')->references('id')->on('users');
            $table->timestamps();
            $table->softDeletes();
        });
        $amenities = [
            "restaurant",
            "cafe",
            "fast_food",
            "pub",
            "bar",
            "bank",
            "atm",
            "school",
            "university",
            "hospital",
            "pharmacy",
            "toilets",
            "parking",
            "theatre",
            "sports_centre",
            "gym",
            "post_office",
            "museum",
            "cinema",
            "public_building",
            "place_of_worship",
            "police",
            "fire_station",
            "waste_basket",
            "charging_station",
            "vending_machine",
            "social_facility",
            "coworking_space",
            "internet_cafe",
            "clinic",
            "nightclub",
            "sauna",
            "massage",
            "wedding_couple",
            "swimming_pool",
            "shelter",
            "ice_cream",
            "college",
            "art_gallery",
            "social_center",
            "yoga",
            "adult_gym",
            "stripclub",
            "public_bath",
            "boarding_house",
            "conference_centre",
            "language_school",
            "music_school",
            "kindergarten",
            "community_centre",
            "private_school",
            "vocational_school",
            "drinking_water",
            "library",
            "hostel",
            "sports_hall",
            "youth_centre",
            "playground",
            "gymnastics",
            "sports_field",
            "basketball_court",
            "tennis_court",
            "football_pitch",
            "handball_court",
            "skateboard_park",
            "bowling_alley",
            "fishing",
            "hunting",
            "bus_station",
            "train_station",
            "subway_station",
            "taxi",
            "car_rental",
            "bike_rental",
            "airport",
            "bus_stop",
            "crosswalk",
            "ferry_terminal",
            "marina",
            "parking_space",
            "parking_entrance",
            "parking_lot",
            "car_sharing",
            "bicycle_parking",
            "motorcycle_parking",
            "bicycle_rental",
            "car_wash",
            "dog_park",
            "sports_complex",
            "climbing",
            "running_track",
            "skating_rink",
            "miniature_golf",
            "petting_zoo",
            "fish_market",
            "greengrocer",
            "outdoor_seating",
            "shop",
            "supermarket",
            "hardware_store",
            "butcher",
            "bakery",
            "deli",
            "health_food",
            "furniture_store",
            "convenience_store",
            "liquor_store",
            "store",
            "newsagent",
            "clothing_store",
            "jewelry_store",
            "electronics_store",
            "toy_store",
            "art_shop",
            "auto_parts_shop",
            "pet_store",
            "bicycle_shop",
            "car_parts",
            "sports_shop",
            "antiques_shop",
            "houseware_store",
            "video_rental",
            "photo_shop",
            "bookstore",
            "flower_shop",
            "music_shop",
            "computer_shop",
            "stationery_shop",
            "cosmetics_shop",
            "camera_shop",
            "second_hand_shop",
            "home_improvement",
            "stationery",
            "electronics",
            "home_appliance_shop",
            "garden_centre",
            "car_repair",
            "automobile",
            "motorcycle",
            "pet_shop",
            "cleaning",
            "laundry",
            "dry_cleaning",
            "iron_shop",
            "shoe_repair",
            "locksmith",
            "tailor",
            "carpet_cleaning",
            "funeral_home",
            "florist",
            "wine_shop",
            "gift_shop",
            "internet_shop"
        ];
        foreach ($amenities as $u) {
            NearLocationFilter::create(['code' => ucwords(str_replace('_', ' ', $u)), 'description' => $u]);
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('near_location_filters');
    }
};
